### PR TITLE
Improved duration parser function

### PR DESCRIPTION
**Pull request by kwaaak**
Fixes https://github.com/sopel-irc/sopel-youtube/issues/8

### CODE REVIEW

**Comment by maxpowa** [comment]
I'm personally not a fan of code duplication like this, could be better using the original loop but slightly refactored.

``` python
    for key in ['y', 'mo', 'w', ... ]:
        if splitdur[key] is not None:
            dur.append(splitdur[key].lower())
```

**Review by macleivo — CHANGES_REQUESTED** [review]
This looks quite good to me, but it might be wise to include a condition `key in splitdur`, should Google remove some fields like 'y' from the API.

**Comment by kwaaak** [comment]
I think ISO8601_PERIOD_REGEX makes sure that all those keys will be in splitdur

**Comment by maxpowa** [comment]
@kwaaak Yes, that's correct. Named groups in python's regex will always exist in the resulting match, they will just be `None` if they aren't found in the input. See [docs](https://docs.python.org/2/library/re.html#re.MatchObject.groupdict).

**Pull request merged**
