### PR TITLE
youtube: use Sopel 7 URL handler API

### PR DESCRIPTION
**Pull request by RustyBower**

### CODE REVIEW

**Comment by dgw** [comment]
@RustyBower Might as well make this go the whole nine yards and use the new URL callback registration API for Sopel 7, if you want. If you don't want, I'm happy to take this as-is. :smile_cat:

**Comment by RustyBower** [comment]
Sure! Let me update this

**Comment by dgw** [comment]
With apologies to @RustyBower 🙏 (I know you're _always_ really busy), this needs rebasing now because I decided to apply your original Sopel 6.x–compatible fix in #16 for immediate release.

**Comment by dgw** [comment]
@RustyBower Actually, I think all the requirements to make the `@url` decorator work properly in Sopel 7 have been merged. You could go straight to that and skip the `register_url_callback` business altogether.

Not only is it easier, but it's also backwards-compatible with Sopel 6 (`@url` was added in Sopel 6.5.0). That said, the `@url` decorator is more than a little wonky in the 6.x series, so you'd be best off updating `requirements.txt` to `sopel>=7.0,<8` anyway.

**Comment by RustyBower** [comment]
Apparently I missed the shutdown function for the new URL handler :D

**Comment by dgw** [comment]
So, having forgotten about this PR until you bumped it just now, I think it would be better to:

* Start fresh from current `master`
* Remove the URL-callback-registration stuff completely and switch to the `@url` decorator (currently uses `@rule`, which is _why_ the callbacks need to be registered manually)
* Replace the `global API` variable with (for example) `bot.memory['youtube_api_client']`, created in `setup()` and safely removed from memory in `shutdown()`
* Keep the requirements change to `sopel>=7.0,<8`, since, while it should _technically_ work in Sopel 6.5+, the behavior of `@url` before 7.0 is screwy (as mentioned previously)
* Force-push over this PR's branch (though the branchname then becomes misleading, oh well)

I think that's everything. Suggested starting fresh from current `master` because the commit history of this PR is a royal mess with all the merges from upstream. 😅

**Comment by RustyBower** [comment]
Should be gucci gang now. Not sure what to do with requirements.txt, so let me know and I can push one more to this.

**Comment by dgw** [comment]
The requirements are 👌 as-is!

I went ahead and eliminated the global `API` variable, so you wouldn't have to do that.

**Review by dgw — APPROVED** [review]
I touched this myself, so me approving it is somewhat hokey, but… nobody else will. 😛

**Pull request merged**
