### PR TITLE
youtube: fix traceback on reconnect

### PR DESCRIPTION
**Pull request by RustyBower**

### CODE REVIEW

**Comment by dgw** [comment]
What does the version compatibility spread look like on this? Is this patch mutually exclusive with #12, which caps the version of the dependency that this touches.

**Comment by RustyBower** [comment]
I actually think this supersedes #12, since that just bandaids the symptoms, and this should fix the root problem. I'm gonna spin up a few test instances and test this with all the different versions of sopel.

**Comment by dgw** [comment]
I'm just wondering if we need a minimum version now, because `cache_discovery` might have been added some time into the life of that library.

**Comment by RustyBower** [comment]
Looks like this was implemented in 1.4.2, but we already pin google-api-python-client>=1.5.5,<1.6, so we should be set.

**Review by dgw — APPROVED** [review]
Hooray, bugfixes!

Can go in a patch version despite requirements edit because nothing is being dropped.

**Pull request merged**
